Book details 1 and 2 added
wolox-training/ec-angular pull request #1
Opened 2020-02-04 19:27 UTC by carzoglioemanuel

## Summary

- Completed book details 1 (description) and 2 (image).

## Screenshot

![image](https://user-images.githubusercontent.com/26333195/73779119-ff16a100-476a-11ea-91e7-a457f92bf875.png)

## Trello Card

https://trello.com/c/nq1oXtB3/26-detalle-de-libro-i-textos
https://trello.com/c/QFyh9fRX/27-detalle-de-libro-ii-imagen

2020-02-04 19:52 UTC, SaraIsabelSantacruz requested changes
Great Job. 👏 👏

2020-02-04 19:52 UTC, SaraIsabelSantacruz commented on scss/details.scss
> +}
if you going to use the same font family in all project texts, you can set it with a *

2020-02-04 19:52 UTC, SaraIsabelSantacruz commented on scss/details.scss
> +}
order alphabetically

2020-02-04 21:13 UTC, martinmona requested changes

2020-02-04 21:13 UTC, martinmona commented on scss/details.scss
> +  &::before {
for nested blocks add one blank line

2020-02-04 21:13 UTC, martinmona commented on scss/application.scss
> +@import 'equalizer', 'details';
import google fonts

`@import url('https://fonts.googleapis.com/css?family=Roboto&display=swap');`

2020-02-04 21:13 UTC, martinmona commented on scss/details.scss
> +  width: 900px;
add `max-width: 100%;` rule

2020-02-04 21:13 UTC, martinmona commented on scss/details.scss
> +    width: 540px;
same

2020-02-04 21:13 UTC, martinmona commented on .gitignore
> +.DS_Store
Add end of file (empty line)

2020-02-04 21:13 UTC, martinmona commented on index.html
> +</html>
Add EOF (end of file)

2020-02-04 21:13 UTC, martinmona commented on scss/details.scss
> +}
Add end of file (empty line)

2020-02-04 21:13 UTC, martinmona commented on scss/variables/_colors.scss
> +$white: #fff;
same

2020-02-04 21:13 UTC, martinmona commented on index.html
> +
remove empty line

2020-02-05 14:46 UTC, martinmona commented on .gitignore
> +.DS_Store
add End of File

2020-02-06 04:12 UTC, SaraIsabelSantacruz approved these changes

2020-02-06 15:07 UTC, martinmona approved these changes

2020-02-06 19:31 UTC, nvescio requested changes

2020-02-06 19:31 UTC, nvescio commented on index.html
> +      <img class="book-cover" src="assets/book-cover.png" />
`img` tags always have to have an `alt` attribute --> `<img class="book-cover" src="assets/book-cover.png" alt="book cover"/>`

2020-02-06 19:31 UTC, nvescio commented on scss/details.scss
> +  width: 261px;
I think it's no necessary to set both `height` and `width`

2020-02-14 12:47 UTC, nvescio approved these changes

2020-02-21 19:02 UTC, merged