Books list
wolox-training/ec-angular pull request #3
Opened 2020-02-06 18:27 UTC by carzoglioemanuel

## Summary

- Books list added

## Screenshot

![image](https://user-images.githubusercontent.com/26333195/73966609-1d100d00-48f5-11ea-8924-164806291bc4.png)

## Trello Card

https://trello.com/c/6w6cqZqs/30-listado-de-libros

2020-02-07 14:06 UTC, martinmona requested changes

2020-02-07 14:06 UTC, martinmona commented on books.html
> +        <div class="book-presentation">
i think these divs aren't necessary

2020-02-07 14:06 UTC, martinmona commented on books.html
> +          <p class="book-detail-presentation">Autor del libro</p>
the span tag would look better

2020-02-10 22:09 UTC, martinmona commented on scss/variables/_variables.scss
> +$book-detail-font-size: 20px;
Maybe you wanna use this values in another places, so the name would be more generic like _$regular-font-size_

2020-02-10 22:09 UTC, martinmona commented on scss/variables/_variables.scss
> +$book-detail-font-size: 20px;
Also, isn't necessary to put everything into variables :laughing:

2020-02-14 12:51 UTC, nvescio approved these changes

2020-02-21 19:03 UTC, merged